# Generated by Django 2.1 on 2018-08-16 07:20

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('marketboard', '0002_auto_20180812_1720'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='created',
            field=model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='modified',
            field=model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='server',
            field=models.CharField(choices=[('Aegis', 'Aegis'), ('Atomos', 'Atomos'), ('Carbuncle', 'Carbuncle'), ('Garuda', 'Garuda'), ('Gungnir', 'Gungnir'), ('Kujata', 'Kujata'), ('Ramuh', 'Ramuh'), ('Tonberry', 'Tonberry'), ('Typhon', 'Typhon'), ('Unicorn', 'Unicorn'), ('Alexander', 'Alexander'), ('Bahamut', 'Bahamut'), ('Durandal', 'Durandal'), ('Fenrir', 'Fenrir'), ('Ifrit', 'Ifrit'), ('Ridill', 'Ridill'), ('Tiamat', 'Tiamat'), ('Ultima', 'Ultima'), ('Valefor', 'Valefor'), ('Yojimbo', 'Yojimbo'), ('Zeromus', 'Zeromus'), ('Anima', 'Anima'), ('Asura', 'Asura'), ('Belias', 'Belias'), ('Chocobo', 'Chocobo'), ('Hades', 'Hades'), ('Ixion', 'Ixion'), ('Mandragora', 'Mandragora'), ('Masamune', 'Masamune'), ('Pandemonium', 'Pandemonium'), ('Shinryu', 'Shinryu'), ('Titan', 'Titan'), ('Adamantoise', 'Adamantoise'), ('Balmung', 'Balmung'), ('Cactuar', 'Cactuar'), ('Coeurl', 'Coeurl'), ('Fairy', 'Fairy'), ('Gilgamesh', 'Gilgamesh'), ('Goblin', 'Goblin'), ('Jenova', 'Jenova'), ('Mateus', 'Mateus'), ('Midgardsormr', 'Midgardsormr'), ('Sargatanas', 'Sargatanas'), ('Siren', 'Siren'), ('Zalera', 'Zalera'), ('Behemoth', 'Behemoth'), ('Brynhildr', 'Brynhildr'), ('Diabolos', 'Diabolos'), ('Excalibur', 'Excalibur'), ('Exodus', 'Exodus'), ('Famfrit', 'Famfrit'), ('Hyperion', 'Hyperion'), ('Lamia', 'Lamia'), ('Leviathan', 'Leviathan'), ('Malboro', 'Malboro'), ('Ultros', 'Ultros'), ('Cerberus', 'Cerberus'), ('Lich', 'Lich'), ('Louisoix', 'Louisoix'), ('Moogle', 'Moogle'), ('Odin', 'Odin'), ('Omega', 'Omega'), ('Phoenix', 'Phoenix'), ('Ragnarok', 'Ragnarok'), ('Shiva', 'Shiva'), ('Zodiark', 'Zodiark')], default='', max_length=15),
            preserve_default=False,
        ),
    ]
